name: Movie Management Workflow

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Collect Workflow Telemetry
        uses: runforesight/foresight-workflow-kit-action@v1
        if: success() || failure()
        with:
          api_key: b983b8fb-e108-483a-bcd7-fdabdb16944a
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - run: npm ci
      - run: npm run coverage
      - name: Foresight test kit
        if: success() || failure()
        uses: runforesight/foresight-test-kit-action@v1
        with:
          api_key: b983b8fb-e108-483a-bcd7-fdabdb16944a
          test_format: JUNIT
          test_framework: JEST
          test_path: junit.xml
          coverage_format: COBERTURA/XML
          coverage_path: ./coverage/cobertura-coverage.xml